import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { HashRouter, Link, Navigate, Route, Routes, useLocation } from 'react-router-dom'
import i18n from 'i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
import { initReactI18next, useTranslation } from 'react-i18next'
import './styles.css'

const copy = {
  en: {
    nav: ['Sessions', 'Activities', 'Programs', 'Resources', 'About'],
    book: 'Book a session',
    heroBrand: 'House of Hoki',
    eyebrow: 'Well-being · personal growth · community',
    titleA: 'A place to arrive.',
    titleB: 'Space to become.',
    intro: 'House of Hoki brings thoughtful private sessions, shared activities and community programs together under one calm roof — online, near Heidelberg and soon in Yerevan.',
    orient: 'Free 15-min orientation',
    explore: 'Explore what we offer',
    sectionKicker: 'Three ways to begin',
    sectionTitle: 'One-to-one. Together. In community.',
    sectionIntro: 'Choose the setting that feels right today. Every request is reviewed by Sarah, with time to understand what you need before anything is confirmed.',
    privateTitle: 'Private sessions',
    privateText: 'Focused, one-to-one space shaped around your goals, preferred format and pace.',
    coupleTitle: 'Couple sessions',
    coupleText: 'A shared space for two adults to explore communication, transitions and reconnection.',
    groupTitle: 'Monthly group sessions',
    groupText: 'Guided circles and workshops for reflection, connection and practical growth.',
    availability:'Availability', usuallyAvailable:'Usually available', monthlySoon:'Monthly · date and location coming soon',
    from: 'Starting from',
    estimate: 'Start questionnaire',
    seeActivities: 'View group sessions',
    programsKicker: 'One house, several doors',
    programsTitle: 'Programs that grow with their communities.',
    commonText: 'A free Armenia-based community pilot for people aged 18–45, beginning with a facilitated discussion circle.',
    youthText: 'Coming-soon programs for ages 16–29, shaped locally for Germany and Armenia.',
    apply: 'Apply to the pilot',
    interest: 'Register interest',
    processKicker: 'A thoughtful first step',
    processTitle: 'Explore first. Share only when ready.',
    steps: [
      ['1', 'Explore anonymously', 'Answer a few practical questions. No name, email or sensitive history required.'],
      ['2', 'Choose a preferred time', 'Private and couple visitors can request one time and add a backup before sharing contact details.'],
      ['3', 'Review and request', 'Sarah reviews every request before a booking and calendar invitation are confirmed.']
    ],
    quote: '“Hoki” means spirit — the part of us that seeks meaning, connection and room to grow.',
    locationTitle: 'Rooted in two places.',
    heidelberg: 'Near Heidelberg',
    yerevan: 'Yerevan · coming soon',
    online: 'Online · wherever you are',
    faqTitle: 'Questions, answered gently.',
    faq: [
      ['What happens in a first session?', 'The first meeting is a chance to talk about what brings you here, ask questions and consider a helpful next step. You do not need to arrive with everything clearly defined.'],
      ['How do I know if this is the right fit?', 'Feeling safe and understood matters. Use the orientation call or first session to notice whether Sarah’s approach, pace and format feel comfortable.'],
      ['What if I do not know what to say?', 'That is completely okay. Gentle questions can help you begin, and you can share only what feels relevant.'],
      ['How long might support take?', 'It depends on your goals, circumstances and preferred pace. Sarah will discuss a starting plan with you and revisit it together.'],
      ['Is House of Hoki an emergency service?', 'No. If you or someone else is in immediate danger, contact local emergency services or use the verified urgent-support links on this website.']
    ],
    footer: 'A space to connect, reflect and grow.',
    bookingKicker: 'Private by design', bookingTitle: 'Plan your session.', bookingIntro: 'Choose private, couple or group support. Pricing stays hidden until the future AI rules are configured and Sarah approves the request.',
  },
  de: {
    nav: ['Sitzungen', 'Aktivitäten', 'Programme', 'Ressourcen', 'Über uns'], book: 'Sitzung buchen',
    heroBrand: 'House of Hoki', eyebrow: 'Wohlbefinden · persönliches Wachstum · Gemeinschaft', titleA: 'Ein Ort zum Ankommen.', titleB: 'Raum zum Wachsen.',
    intro: 'House of Hoki vereint persönliche Sitzungen, gemeinsame Aktivitäten und Community-Programme unter einem ruhigen Dach — online, bei Heidelberg und bald in Jerewan.',
    orient: 'Kostenlose 15-Min.-Orientierung', explore: 'Angebot entdecken', sectionKicker: 'Drei Wege zum Anfang', sectionTitle: 'Allein. Gemeinsam. In der Gruppe.',
    sectionIntro: 'Wähle den Rahmen, der heute zu dir passt. Sarah prüft jede Anfrage persönlich, bevor etwas bestätigt wird.',
    privateTitle: 'Private Sitzungen', privateText: 'Ein fokussierter Raum, abgestimmt auf deine Ziele, dein Format und dein Tempo.', coupleTitle:'Paarsitzungen', coupleText:'Ein gemeinsamer Raum für zwei Erwachsene rund um Kommunikation, Veränderungen und Wiederannäherung.', groupTitle: 'Monatliche Gruppensitzungen', groupText: 'Begleitete Kreise und Workshops für Reflexion, Verbindung und praktisches Wachstum.', availability:'Verfügbarkeit', usuallyAvailable:'In der Regel verfügbar', monthlySoon:'Monatlich · Termin und Ort folgen',
    from: 'Ab', estimate: 'Fragebogen starten', seeActivities: 'Gruppensitzungen ansehen', programsKicker: 'Ein Haus, mehrere Türen', programsTitle: 'Programme, die mit ihrer Gemeinschaft wachsen.',
    commonText: 'Ein kostenloses Community-Pilotprojekt in Armenien für 18- bis 45-Jährige, beginnend mit einem moderierten Gesprächskreis.', youthText: 'Programme für 16- bis 29-Jährige in Deutschland und Armenien — demnächst.', apply: 'Für Pilot bewerben', interest: 'Interesse anmelden',
    processKicker: 'Ein achtsamer erster Schritt', processTitle: 'Erst erkunden. Teilen, wenn du bereit bist.', steps: [['1','Anonym erkunden','Beantworte praktische Fragen — ohne Namen, E-Mail oder sensible Vorgeschichte.'],['2','Wunschtermin wählen','Für Privat- und Paarsitzungen kannst du einen Termin und eine Alternative anfragen.'],['3','Prüfen und anfragen','Sarah prüft jede Anfrage vor Buchungsbestätigung und Kalendereinladung.']],
    quote: '„Hoki“ bedeutet Geist — der Teil in uns, der Sinn, Verbindung und Raum zum Wachsen sucht.', locationTitle: 'In zwei Orten verwurzelt.', heidelberg: 'Bei Heidelberg', yerevan: 'Jerewan · demnächst', online: 'Online · wo du bist', faqTitle: 'Fragen, behutsam beantwortet.',
    faq: [['Was passiert in einer ersten Sitzung?','Das erste Gespräch bietet Raum, dein Anliegen zu schildern, Fragen zu stellen und einen hilfreichen nächsten Schritt zu finden. Du musst noch nicht alles klar benennen können.'],['Woran merke ich, ob es zwischenmenschlich passt?','Sich sicher und verstanden zu fühlen, ist wichtig. Nutze das Orientierungsgespräch oder die erste Sitzung, um Sarahs Arbeitsweise, Tempo und Format kennenzulernen.'],['Was, wenn ich nicht weiß, was ich sagen soll?','Das ist völlig in Ordnung. Behutsame Fragen können den Anfang erleichtern, und du teilst nur, was sich relevant anfühlt.'],['Wie lange kann eine Begleitung dauern?','Das hängt von deinen Zielen, deiner Situation und deinem Tempo ab. Sarah bespricht mit dir einen ersten Plan und passt ihn gemeinsam mit dir an.'],['Ist House of Hoki ein Notfalldienst?','Nein. Bei unmittelbarer Gefahr kontaktiere den örtlichen Notruf oder nutze die geprüften Akuthilfe-Links auf dieser Website.']],
    footer: 'Ein Raum für Verbindung, Reflexion und Wachstum.',
    bookingKicker: 'Vertraulich gestaltet', bookingTitle: 'Plane deine Sitzung.', bookingIntro: 'Wähle private, Paar- oder Gruppenbegleitung. Preise bleiben verborgen, bis die KI-Regeln konfiguriert sind und Sarah die Anfrage bestätigt.',
  },
  hy: {
    nav: ['Անհատական', 'Խմբային', 'Ծրագրեր', 'Նյութեր', 'Մեր մասին'], book: 'Ամրագրել հանդիպում',
    heroBrand: 'House of Hoki', eyebrow: 'Բարեկեցություն · անձնական աճ · համայնք', titleA: 'Վայր՝ կանգ առնելու։', titleB: 'Տարածք՝ դառնալու։',
    intro: 'House of Hoki-ն միավորում է անհատական հանդիպումները, խմբային գործունեությունն ու համայնքային ծրագրերը՝ առցանց, Հայդելբերգի մոտ և շուտով Երևանում։',
    orient: 'Անվճար 15 րոպե ծանոթացում', explore: 'Բացահայտել առաջարկները', sectionKicker: 'Սկսելու երեք ճանապարհ', sectionTitle: 'Անհատապես։ Միասին։ Համայնքում։',
    sectionIntro: 'Ընտրեք այն միջավայրը, որը հիմա ձեզ հարմար է։ Սառան անձամբ դիտարկում է յուրաքանչյուր հարցում։', privateTitle: 'Անհատական հանդիպումներ', privateText: 'Կենտրոնացված անհատական տարածք՝ ձեր նպատակներին ու տեմպին համապատասխան։', coupleTitle:'Զույգերի հանդիպումներ', coupleText:'Համատեղ տարածք երկու չափահասների համար՝ հաղորդակցության, փոփոխությունների և վերամերձեցման շուրջ։', groupTitle: 'Ամսական խմբային հանդիպումներ', groupText: 'Ուղղորդված շրջաններ և աշխատարաններ՝ մտորելու, կապվելու և աճելու համար։', availability:'Հասանելիություն', usuallyAvailable:'Սովորաբար հասանելի', monthlySoon:'Ամսական · ամսաթիվն ու վայրը՝ շուտով',
    from: 'Սկսած', estimate: 'Սկսել հարցաշարը', seeActivities: 'Դիտել խմբային հանդիպումները', programsKicker: 'Մեկ տուն, մի քանի դուռ', programsTitle: 'Ծրագրեր, որոնք աճում են իրենց համայնքների հետ։',
    commonText: 'Անվճար համայնքային փորձնական ծրագիր Հայաստանում՝ 18–45 տարեկանների համար, որը սկսվում է քննարկման շրջանակից։', youthText: 'Շուտով՝ ծրագրեր 16–29 տարեկանների համար՝ Գերմանիայում և Հայաստանում։', apply: 'Դիմել փորձնական ծրագրին', interest: 'Գրանցել հետաքրքրությունը',
    processKicker: 'Խոհուն առաջին քայլ', processTitle: 'Նախ ուսումնասիրեք։ Կիսվեք՝ երբ պատրաստ լինեք։', steps: [['1','Ուսումնասիրել անանուն','Պատասխանեք մի քանի գործնական հարցի՝ առանց անվան կամ զգայուն պատմության։'],['2','Ընտրել նախընտրելի ժամ','Անհատական և զույգերի հանդիպումների համար կարող եք ընտրել հիմնական և այլընտրանքային ժամ։'],['3','Ստուգել և ուղարկել','Սառան ստուգում է հարցումը նախքան ամրագրման և օրացույցի հաստատումը։']],
    quote: '«Հոգի»-ն մեր այն մասն է, որը փնտրում է իմաստ, կապ և աճելու տարածք։', locationTitle: 'Արմատավորված երկու վայրում։', heidelberg: 'Հայդելբերգի մոտ', yerevan: 'Երևան · շուտով', online: 'Առցանց · որտեղ էլ լինեք', faqTitle: 'Հարցեր՝ մեղմ պատասխաններով։',
    faq: [['Ի՞նչ է տեղի ունենում առաջին հանդիպման ընթացքում։','Առաջին զրույցը հնարավորություն է պատմելու, թե ինչն է ձեզ այստեղ բերել, հարցեր տալու և օգտակար հաջորդ քայլը միասին գտնելու։ Պարտադիր չէ ամեն ինչ նախապես հստակ ձևակերպել։'],['Ինչպե՞ս իմանամ, որ այս մոտեցումն ինձ հարմար է։','Անվտանգ և հասկացված զգալը կարևոր է։ Ծանոթացման զանգը կամ առաջին հանդիպումը կարող է օգնել հասկանալ՝ արդյոք Սառայի մոտեցումը, տեմպն ու ձևաչափը հարմար են ձեզ։'],['Ի՞նչ անել, եթե չգիտեմ՝ ինչ ասել։','Դա լիովին բնական է։ Մեղմ հարցերը կարող են օգնել սկսել, իսկ դուք կարող եք կիսվել միայն նրանով, ինչն անհրաժեշտ եք համարում։'],['Որքա՞ն կարող է տևել աջակցությունը։','Դա կախված է ձեր նպատակներից, իրավիճակից և նախընտրելի տեմպից։ Սառան ձեզ հետ կքննարկի մեկնարկային պլանը և անհրաժեշտության դեպքում միասին կվերանայի այն։'],['House of Hoki-ն շտապ օգնության ծառայությո՞ւն է։','Ոչ։ Անմիջական վտանգի դեպքում դիմեք տեղական շտապ ծառայությանը կամ օգտվեք կայքի ստուգված շտապ աջակցության հղումներից։']],
    footer: 'Տարածք՝ կապվելու, խորհելու և աճելու համար։',
    bookingKicker: 'Գաղտնիությունը՝ առաջնային', bookingTitle: 'Պլանավորեք ձեր հանդիպումը։', bookingIntro: 'Ընտրեք անհատական, զույգերի կամ խմբային աջակցություն։ Գները չեն ցուցադրվի մինչև ԱԲ կանոնների կարգավորումն ու Սառայի հաստատումը։',
  }
}

const extraCopy = {
  en: {
    language:'Language', menuOpen:'Open menu', menuClose:'Close menu', menuTitle:'Quick access', region:'Region', chooseRegion:'Choose region', regions:{de:'Germany',am:'Armenia'}, brandDescriptor:'Well-being · community',
    cookieBanner:{title:'Your privacy choices',text:'We use necessary cookies to operate this website. With your consent, a preference cookie remembers your chosen language. Analytics and marketing cookies are currently disabled.',customize:'Manage choices',reject:'Reject optional cookies',accept:'Accept preferences',settingsTitle:'Cookie preferences',necessary:'Necessary cookies',necessaryText:'Required for your consent choice and core website operation. Always active.',preferenceCategory:'Language preference',preferenceText:'Remembers the language you select on this device.',save:'Save choices',policy:'Read our cookie notice'},
    trust:['English · German · Armenian','Online & in person','Private by design'], reflectionKicker:'Everyday psychology', reflectionTitle:'The questions beneath the surface.', reflectionIntro:'You do not need the perfect words before you begin. Sometimes a small, honest question is enough to open a new direction.', reflectionQuestions:['Why do I keep overthinking the same things?','How can I set boundaries without feeling guilty?','Why do I feel overwhelmed when everything looks fine?','Can talking help me change old patterns?','How do I become kinder to myself?','What would feeling more like myself look like?'], therapyImageAlt:'A therapist and a client having a calm conversation in a welcoming room', per60:'/ 60 min', free:'Free', pilotActivities:'Pilot activities', statuses:['Pilot · Armenia','Germany · coming soon','Armenia · coming soon'],
    locationDetails:['Private sessions · weekdays','Programs · community · sessions','English · German · Armenian'], ctaKicker:'Your first step can be small',
    details:{orientation:'Ask for a 15-min orientation',expect:'What to expect',clear:'Clear information before commitment.',expectA:'Begin with a service-specific questionnaire. It collects practical preferences without using emotional intensity to set a price.',expectB:'Sarah reviews every request. A time, session plan and final price are confirmed before any payment is requested.'},
    listing:{sessionsTitle:'Sessions made personal.',activitiesTitle:'Activities made to connect.',sessionsIntro:'Choose private, couple or monthly group support. Pricing will be added only after the future guidance rules are approved.',activitiesIntro:'Explore current pilots and the group formats planned for the House of Hoki community.',private:'Private session',privateMeta:'One-to-one · usually available',couple:'Couple session',coupleMeta:'Two adults · usually available',group:'Monthly group session',groupMeta:'Date and location · coming soon',discussion:'Discussion circle',discussionMeta:'Common Club pilot · Yerevan',community:'Community activities',communityMeta:'More formats will follow the pilot.',explore:'Explore →',programsKicker:'One house · several doors',programsTitle:'Programs with their own purpose.',open:'Open program →'},
    orientationPage:{kicker:'Free · 15 minutes',title:'Start with a short conversation.',intro:'Request a normal call or WhatsApp orientation. Sarah reviews each request before confirming a time.',email:'Request by email',other:'Other contact options',facts:[['Length','15 minutes'],['Cost','Free'],['Confirmation','Sarah approves']]},
    contactPage:{kicker:'Contact',title:'Choose what feels comfortable.',intro:'Business email is available now. Separate German and Armenian WhatsApp, phone and Telegram details will be added after verification.',germany:'Germany',germanyText:'WhatsApp + phone · coming soon',armenia:'Armenia',armeniaText:'WhatsApp + phone + Telegram · coming soon'},
    crisis:{title:'Need urgent support?',text:'House of Hoki is not an emergency service. If you or someone else is in immediate danger, contact local emergency services.',link:'View verified support contacts →'},
    emergency:{kicker:'Immediate support',title:'You do not have to handle a crisis alone.',intro:'These external services are independent from House of Hoki. Availability can change; use the linked official source for current details.',cards:[['Germany · immediate danger','Call 112','Official German guidance ↗'],['Germany · emotional crisis','Call 116 123','TelefonSeelsorge ↗'],['Armenia · immediate danger','Call 112','Armenian Ministry of Internal Affairs ↗'],['Yerevan · emotional support','0800 00 900','Yerevan Municipality information ↗']]},
    pages:{about:['About','A home for thoughtful growth.','House of Hoki is developing as an umbrella platform for private sessions, shared activities and independently owned community programs.','Sarah’s final professional title, biography and qualifications will be published only after they are confirmed.'],resources:['Resources','Useful ideas, carefully shared.','Articles, frequently asked questions and practical well-being resources will be added after editorial and professional review.'],privacy:['Launch draft','Privacy notice','Intended controller: House of Hoki, Armenia. Privacy contact: info@houseofhoki.com. The legal entity and service address are still being established and must be completed before production bookings begin.','The website currently stores only the cookie choice and, with permission, the selected language on the visitor’s device. Analytics and marketing tracking are disabled.','When secure booking is activated, practical questionnaire answers and contact details will be used to review the request, obtain Sarah’s approval, send confirmations and create the calendar invitation. Health diagnoses and unnecessary sensitive histories should not be requested.','The production notice will identify Cloudflare, n8n, the calendar provider and any payment provider, together with purposes, legal bases, retention periods, international-transfer safeguards and data-subject rights. This draft requires professional legal review before launch.'],cookies:['Current configuration','Cookie notice','hoki_cookie_choice is a necessary cookie used to remember whether optional preferences were accepted. It lasts for up to 12 months.','hoki_lang stores the selected language only after permission is given and lasts for up to 12 months. It can be removed at any time through Cookie preferences in the footer.','No analytics, advertising or cross-site marketing cookies are currently enabled. If that changes, those services must remain disabled until valid consent is recorded.'],imprint:['Formation pending','Legal information','House of Hoki — intended business name. Country of establishment: Armenia.','Service and postal address: not yet established. This information must be completed before the public commercial launch.','Email: info@houseofhoki.com. Registration, tax, representative and professional-regulatory details will be added when formally available.']},
    footerLinks:['Services','Programs','Resources','Contact'], legalLinks:['Privacy','Cookies','Imprint'], ageNote:'18+ general services'
  },
  de: {
    language:'Sprache', menuOpen:'Menü öffnen', menuClose:'Menü schließen', menuTitle:'Schnellzugriff', region:'Region', chooseRegion:'Region wählen', regions:{de:'Deutschland',am:'Armenien'}, brandDescriptor:'Wohlbefinden · Gemeinschaft', trust:['Englisch · Deutsch · Armenisch','Online & vor Ort','Vertraulich gestaltet'], reflectionKicker:'Psychologie im Alltag', reflectionTitle:'Die Fragen unter der Oberfläche.', reflectionIntro:'Du brauchst nicht die perfekten Worte, um zu beginnen. Manchmal öffnet schon eine kleine, ehrliche Frage eine neue Richtung.', reflectionQuestions:['Warum denke ich immer wieder über dieselben Dinge nach?','Wie kann ich Grenzen setzen, ohne mich schuldig zu fühlen?','Warum bin ich überfordert, obwohl alles in Ordnung wirkt?','Kann ein Gespräch helfen, alte Muster zu verändern?','Wie kann ich freundlicher mit mir selbst werden?','Wie würde es sich anfühlen, wieder mehr ich selbst zu sein?'], therapyImageAlt:'Eine Therapeutin und eine Klientin in einem ruhigen Gespräch in einem einladenden Raum', per60:'/ 60 Min.', free:'Kostenlos', pilotActivities:'Pilotaktivitäten', statuses:['Pilot · Armenien','Deutschland · demnächst','Armenien · demnächst'], locationDetails:['Private Sitzungen · werktags','Programme · Gemeinschaft · Sitzungen','Englisch · Deutsch · Armenisch'], ctaKicker:'Der erste Schritt darf klein sein',
    cookieBanner:{title:'Deine Datenschutzauswahl',text:'Wir verwenden notwendige Cookies für den Betrieb der Website. Mit deiner Einwilligung speichert ein Präferenz-Cookie deine gewählte Sprache. Analyse- und Marketing-Cookies sind derzeit deaktiviert.',customize:'Auswahl verwalten',reject:'Optionale Cookies ablehnen',accept:'Präferenzen akzeptieren',settingsTitle:'Cookie-Einstellungen',necessary:'Notwendige Cookies',necessaryText:'Erforderlich für deine Einwilligungswahl und den Betrieb der Website. Immer aktiv.',preferenceCategory:'Spracheinstellung',preferenceText:'Speichert die von dir gewählte Sprache auf diesem Gerät.',save:'Auswahl speichern',policy:'Cookie-Hinweis lesen'},
    details:{orientation:'15-Min.-Orientierung anfragen',expect:'Was dich erwartet',clear:'Klare Informationen vor der Entscheidung.',expectA:'Beginne mit dem passenden Fragebogen. Praktische Präferenzen werden erfasst, ohne emotionale Belastung zur Preisbildung zu verwenden.',expectB:'Sarah prüft jede Anfrage. Termin, Sitzungsplan und Endpreis werden vor jeder Zahlung bestätigt.'},
    listing:{sessionsTitle:'Sitzungen, persönlich gestaltet.',activitiesTitle:'Aktivitäten, die verbinden.',sessionsIntro:'Wähle private, Paar- oder monatliche Gruppenbegleitung. Preise folgen erst nach Freigabe der künftigen Regeln.',activitiesIntro:'Entdecke aktuelle Pilotprojekte und geplante Gruppenformate.',private:'Private Sitzung',privateMeta:'Individuell · in der Regel verfügbar',couple:'Paarsitzung',coupleMeta:'Zwei Erwachsene · in der Regel verfügbar',group:'Monatliche Gruppensitzung',groupMeta:'Termin und Ort · demnächst',discussion:'Gesprächskreis',discussionMeta:'Common-Club-Pilot · Jerewan',community:'Community-Aktivitäten',communityMeta:'Weitere Formate folgen nach dem Pilotprojekt.',explore:'Entdecken →',programsKicker:'Ein Haus · mehrere Türen',programsTitle:'Programme mit eigenem Ziel.',open:'Programm öffnen →'},
    orientationPage:{kicker:'Kostenlos · 15 Minuten',title:'Beginne mit einem kurzen Gespräch.',intro:'Bitte um ein normales Telefonat oder eine WhatsApp-Orientierung. Sarah bestätigt den Termin persönlich.',email:'Per E-Mail anfragen',other:'Weitere Kontaktwege',facts:[['Dauer','15 Minuten'],['Kosten','Kostenlos'],['Bestätigung','Durch Sarah']]},
    contactPage:{kicker:'Kontakt',title:'Wähle, was sich angenehm anfühlt.',intro:'Die geschäftliche E-Mail ist bereits verfügbar. Deutsche und armenische WhatsApp-, Telefon- und Telegram-Kontakte folgen nach Prüfung.',germany:'Deutschland',germanyText:'WhatsApp + Telefon · demnächst',armenia:'Armenien',armeniaText:'WhatsApp + Telefon + Telegram · demnächst'},
    crisis:{title:'Brauchst du dringend Unterstützung?',text:'House of Hoki ist kein Notfalldienst. Bei unmittelbarer Gefahr wende dich an den örtlichen Notruf.',link:'Geprüfte Hilfskontakte anzeigen →'},
    emergency:{kicker:'Soforthilfe',title:'Du musst eine Krise nicht allein bewältigen.',intro:'Diese externen Dienste sind unabhängig von House of Hoki. Prüfe aktuelle Angaben über die offiziellen Links.',cards:[['Deutschland · unmittelbare Gefahr','112 anrufen','Offizielle deutsche Hinweise ↗'],['Deutschland · seelische Krise','116 123 anrufen','TelefonSeelsorge ↗'],['Armenien · unmittelbare Gefahr','112 anrufen','Armenisches Innenministerium ↗'],['Jerewan · emotionale Unterstützung','0800 00 900','Informationen der Stadt Jerewan ↗']]},
    pages:{about:['Über uns','Ein Zuhause für achtsames Wachstum.','House of Hoki entsteht als Dach für private Sitzungen, gemeinsame Aktivitäten und unabhängig geführte Community-Programme.','Sarahs endgültige Berufsbezeichnung, Biografie und Qualifikationen werden erst nach Bestätigung veröffentlicht.'],resources:['Ressourcen','Nützliche Ideen, sorgfältig geteilt.','Artikel, häufige Fragen und praktische Ressourcen werden nach redaktioneller und fachlicher Prüfung ergänzt.'],privacy:['Entwurf für den Start','Datenschutzhinweis','Vorgesehene verantwortliche Stelle: House of Hoki, Armenien. Datenschutzkontakt: info@houseofhoki.com. Rechtsträger und ladungsfähige Anschrift befinden sich noch in Gründung und müssen vor produktiven Buchungen ergänzt werden.','Aktuell speichert die Website nur die Cookie-Auswahl und nach Einwilligung die gewählte Sprache auf dem Gerät. Analyse- und Marketingtracking sind deaktiviert.','Nach Aktivierung der sicheren Buchung werden praktische Fragebogenantworten und Kontaktdaten zur Prüfung, Freigabe durch Sarah, Bestätigung und Erstellung der Kalendereinladung verwendet. Diagnosen und unnötige sensible Vorgeschichten sollen nicht abgefragt werden.','Der endgültige Hinweis nennt Cloudflare, n8n, den Kalender- und gegebenenfalls Zahlungsanbieter sowie Zwecke, Rechtsgrundlagen, Aufbewahrungsfristen, Drittlandgarantien und Betroffenenrechte. Vor dem Start ist eine professionelle rechtliche Prüfung erforderlich.'],cookies:['Aktuelle Konfiguration','Cookie-Hinweis','hoki_cookie_choice ist ein notwendiges Cookie, das die Auswahl zu optionalen Präferenzen bis zu 12 Monate speichert.','hoki_lang speichert die gewählte Sprache nur nach Einwilligung bis zu 12 Monate. Die Auswahl kann jederzeit über die Cookie-Einstellungen im Footer geändert werden.','Analyse-, Werbe- oder websiteübergreifende Marketing-Cookies sind derzeit nicht aktiv. Künftige Dienste bleiben bis zu einer wirksamen Einwilligung deaktiviert.'],imprint:['Gründung ausstehend','Impressum','House of Hoki — vorgesehener Geschäftsname. Land der Niederlassung: Armenien.','Geschäfts- und Postanschrift: noch nicht festgelegt. Diese Angabe muss vor dem öffentlichen kommerziellen Start ergänzt werden.','E-Mail: info@houseofhoki.com. Register-, Steuer-, Vertretungs- und berufsrechtliche Angaben folgen, sobald sie offiziell vorliegen.']}, footerLinks:['Leistungen','Programme','Ressourcen','Kontakt'],legalLinks:['Datenschutz','Cookies','Impressum'],ageNote:'Allgemeine Angebote ab 18'
  },
  hy: {
    language:'Լեզու', menuOpen:'Բացել ընտրացանկը', menuClose:'Փակել ընտրացանկը', menuTitle:'Արագ մուտք', region:'Տարածաշրջան', chooseRegion:'Ընտրել տարածաշրջանը', regions:{de:'Գերմանիա',am:'Հայաստան'}, brandDescriptor:'Բարեկեցություն · համայնք', trust:['Անգլերեն · Գերմաներեն · Հայերեն','Առցանց և առկա','Գաղտնիությունը՝ առաջնային'], reflectionKicker:'Առօրյա հոգեբանություն', reflectionTitle:'Մակերեսի տակ գտնվող հարցերը։', reflectionIntro:'Սկսելու համար կատարյալ բառեր պետք չեն։ Երբեմն մի փոքր, անկեղծ հարցն արդեն կարող է նոր ուղղություն բացել։', reflectionQuestions:['Ինչո՞ւ եմ նույն բաների մասին կրկին ու կրկին մտածում։','Ինչպե՞ս սահմաններ դնեմ՝ առանց մեղավոր զգալու։','Ինչո՞ւ եմ ծանրաբեռնված զգում, երբ արտաքինից ամեն ինչ լավ է։','Կարո՞ղ է զրույցն օգնել փոխել հին սովորությունները։','Ինչպե՞ս ավելի բարի լինեմ ինքս իմ հանդեպ։','Ինչպիսի՞ն կլիներ նորից ավելի շատ ինքս ինձ նման զգալը։'], therapyImageAlt:'Թերապևտի և այցելուի հանգիստ զրույցը հարմարավետ սենյակում', per60:'/ 60 րոպե', free:'Անվճար', pilotActivities:'Փորձնական միջոցառումներ', statuses:['Փորձնական · Հայաստան','Գերմանիա · շուտով','Հայաստան · շուտով'], locationDetails:['Անհատական հանդիպումներ · աշխատանքային օրերին','Ծրագրեր · համայնք · հանդիպումներ','Անգլերեն · Գերմաներեն · Հայերեն'], ctaKicker:'Առաջին քայլը կարող է փոքր լինել',
    cookieBanner:{title:'Ձեր գաղտնիության ընտրությունը',text:'Կայքի աշխատանքի համար օգտագործում ենք անհրաժեշտ cookie-ներ։ Ձեր համաձայնությամբ նախընտրության cookie-ն հիշում է ընտրված լեզուն։ Վերլուծական և գովազդային cookie-ները այժմ անջատված են։',customize:'Կառավարել ընտրությունը',reject:'Մերժել ոչ պարտադիր cookie-ները',accept:'Ընդունել նախընտրությունները',settingsTitle:'Cookie կարգավորումներ',necessary:'Անհրաժեշտ cookie-ներ',necessaryText:'Անհրաժեշտ է համաձայնության ընտրության և կայքի աշխատանքի համար։ Միշտ ակտիվ է։',preferenceCategory:'Լեզվի նախընտրություն',preferenceText:'Այս սարքում հիշում է ձեր ընտրած լեզուն։',save:'Պահպանել ընտրությունը',policy:'Կարդալ cookie ծանուցումը'},
    details:{orientation:'Դիմել 15 րոպեանոց ծանոթացման համար',expect:'Ինչ սպասել',clear:'Հստակ տեղեկություն՝ նախքան որոշումը։',expectA:'Սկսեք համապատասխան հարցաշարից։ Այն հավաքում է գործնական նախընտրությունները՝ առանց հուզական վիճակը գնի հաշվարկում օգտագործելու։',expectB:'Սառան ուսումնասիրում է յուրաքանչյուր հարցում։ Ժամը, ծրագիրը և վերջնական գինը հաստատվում են վճարումից առաջ։'},
    listing:{sessionsTitle:'Անձնական ձևաչափով հանդիպումներ։',activitiesTitle:'Միավորող միջոցառումներ։',sessionsIntro:'Ընտրեք անհատական, զույգերի կամ ամսական խմբային աջակցություն։ Գները կավելացվեն միայն ապագա կանոնների հաստատումից հետո։',activitiesIntro:'Բացահայտեք ընթացիկ փորձնական և նախատեսվող խմբային ձևաչափերը։',private:'Անհատական հանդիպում',privateMeta:'Անհատապես · սովորաբար հասանելի',couple:'Զույգերի հանդիպում',coupleMeta:'Երկու չափահաս · սովորաբար հասանելի',group:'Ամսական խմբային հանդիպում',groupMeta:'Ամսաթիվն ու վայրը · շուտով',discussion:'Քննարկման շրջան',discussionMeta:'Common Club փորձնական · Երևան',community:'Համայնքային միջոցառումներ',communityMeta:'Նոր ձևաչափեր կավելացվեն փորձնական փուլից հետո։',explore:'Բացահայտել →',programsKicker:'Մեկ տուն · մի քանի դուռ',programsTitle:'Ծրագրեր՝ սեփական նպատակով։',open:'Բացել ծրագիրը →'},
    orientationPage:{kicker:'Անվճար · 15 րոպե',title:'Սկսեք կարճ զրույցից։',intro:'Դիմեք սովորական զանգի կամ WhatsApp ծանոթացման համար։ Սառան հաստատում է յուրաքանչյուր ժամադրություն։',email:'Դիմել էլ. փոստով',other:'Այլ կապի տարբերակներ',facts:[['Տևողություն','15 րոպե'],['Արժեք','Անվճար'],['Հաստատում','Սառայի կողմից']]},
    contactPage:{kicker:'Կապ',title:'Ընտրեք ձեզ հարմար տարբերակը։',intro:'Գործարար էլ. փոստն արդեն հասանելի է։ Գերմանական և հայկական WhatsApp, հեռախոս և Telegram տվյալները կավելացվեն ստուգումից հետո։',germany:'Գերմանիա',germanyText:'WhatsApp + հեռախոս · շուտով',armenia:'Հայաստան',armeniaText:'WhatsApp + հեռախոս + Telegram · շուտով'},
    crisis:{title:'Շտապ աջակցության կարիք ունե՞ք։',text:'House of Hoki-ն շտապ օգնության ծառայություն չէ։ Անմիջական վտանգի դեպքում դիմեք տեղական շտապ ծառայությանը։',link:'Դիտել ստուգված աջակցության տվյալները →'},
    emergency:{kicker:'Անհապաղ աջակցություն',title:'Պարտադիր չէ ճգնաժամը հաղթահարել միայնակ։',intro:'Այս արտաքին ծառայությունները անկախ են House of Hoki-ից։ Ընթացիկ տվյալները ստուգեք պաշտոնական հղումներով։',cards:[['Գերմանիա · անմիջական վտանգ','Զանգահարել 112','Գերմանիայի պաշտոնական ուղեցույց ↗'],['Գերմանիա · հուզական ճգնաժամ','Զանգահարել 116 123','TelefonSeelsorge ↗'],['Հայաստան · անմիջական վտանգ','Զանգահարել 112','ՀՀ ներքին գործերի նախարարություն ↗'],['Երևան · հուզական աջակցություն','0800 00 900','Երևանի քաղաքապետարանի տեղեկություն ↗']]},
    pages:{about:['Մեր մասին','Խոհուն աճի տուն։','House of Hoki-ն զարգանում է որպես անհատական հանդիպումների, ընդհանուր միջոցառումների և անկախ համայնքային ծրագրերի հարթակ։','Սառայի մասնագիտական վերջնական կոչումը, կենսագրությունն ու որակավորումները կհրապարակվեն հաստատվելուց հետո։'],resources:['Նյութեր','Օգտակար մտքեր՝ խնամքով ներկայացված։','Հոդվածները, հաճախ տրվող հարցերն ու գործնական նյութերը կավելացվեն խմբագրական և մասնագիտական ստուգումից հետո։'],privacy:['Մեկնարկային նախագիծ','Գաղտնիության ծանուցում','Նախատեսվող պատասխանատու՝ House of Hoki, Հայաստան։ Գաղտնիության կապ՝ info@houseofhoki.com։ Իրավաբանական կարգավիճակն ու սպասարկման հասցեն դեռ հաստատվում են և պետք է լրացվեն մինչև իրական ամրագրումները։','Այժմ կայքը սարքում պահում է միայն cookie-ի ընտրությունը և, համաձայնության դեպքում, ընտրված լեզուն։ Վերլուծական և գովազդային հետևումը անջատված է։','Անվտանգ ամրագրման ակտիվացումից հետո գործնական պատասխաններն ու կապի տվյալները կօգտագործվեն հարցումը ստուգելու, Սառայի հաստատումը ստանալու և օրացույցի հրավեր ուղարկելու համար։ Անհարկի զգայուն տվյալներ և ախտորոշումներ չեն պահանջվի։','Վերջնական ծանուցումը կնշի Cloudflare-ը, n8n-ը, օրացույցի և վճարման մատակարարներին, նպատակները, իրավական հիմքերը, պահպանման ժամկետները, միջազգային փոխանցումները և օգտատերերի իրավունքները։ Մեկնարկից առաջ անհրաժեշտ է իրավական մասնագիտական ստուգում։'],cookies:['Ընթացիկ կարգավորում','Cookie ծանուցում','hoki_cookie_choice անհրաժեշտ cookie-ն մինչև 12 ամիս հիշում է optional ընտրությունը։','hoki_lang-ը ընտրված լեզուն պահում է միայն համաձայնությունից հետո՝ մինչև 12 ամիս։ Այն կարելի է փոխել footer-ի Cookie կարգավորումներից։','Վերլուծական, գովազդային կամ միջկայքային marketing cookie-ներ այժմ ակտիվ չեն։ Ապագա ծառայությունները կմնան անջատված մինչև վավեր համաձայնությունը։'],imprint:['Գրանցումը դեռ ընթացքի մեջ է','Իրավական տեղեկություններ','House of Hoki — նախատեսվող բիզնես անվանում։ Հիմնադրման երկիր՝ Հայաստան։','Սպասարկման և փոստային հասցե՝ դեռ հաստատված չէ։ Այն պետք է լրացվի մինչև հանրային առևտրային մեկնարկը։','Էլ․ հասցե՝ info@houseofhoki.com։ Գրանցման, հարկային, ներկայացուցչի և մասնագիտական տվյալները կավելացվեն պաշտոնականացումից հետո։']}, footerLinks:['Ծառայություններ','Ծրագրեր','Նյութեր','Կապ'],legalLinks:['Գաղտնիություն','Cookie-ներ','Իրավական տվյալներ'],ageNote:'Ընդհանուր ծառայությունները՝ 18+'
  }
}

Object.keys(copy).forEach(language=>Object.assign(copy[language],extraCopy[language]))
const detector=new LanguageDetector()
i18n.use(detector).use(initReactI18next).init({resources:Object.fromEntries(Object.entries(copy).map(([key,value])=>[key,{translation:value}])),fallbackLng:'en',supportedLngs:['en','de','hy'],load:'languageOnly',interpolation:{escapeValue:false},detection:{order:['cookie','navigator'],lookupCookie:'hoki_lang',caches:[]}})

const programs = [
  { mark: 'CC', name: 'Common Club', status: 'Pilot · Armenia', className: 'clay', path: '/programs/common-club' },
  { mark: 'HY', name: 'Hoki for Youth', status: 'Germany · coming soon', className: 'sage', path: '/programs/hoki-youth-germany' },
  { mark: 'HY', name: 'Hoki for Youth', status: 'Armenia · coming soon', className: 'sand', path: '/programs/hoki-youth-armenia' },
]

function Logo() {
  const { t }=useTranslation()
  return <div className="logo" aria-label="House of Hoki"><span className="logo-mark" aria-hidden="true"><img src={`${import.meta.env.BASE_URL}logo-mark.png`} alt=""/></span><span>House of Hoki<small>{t('brandDescriptor')}</small></span></div>
}

function Header({ lang, setLang }) {
  const { t }=useTranslation()
  const {pathname}=useLocation()
  const [menuOpen,setMenuOpen]=useState(false)
  const paths = ['/sessions','/activities','/programs','/resources','/about']
  const nav=t('nav',{returnObjects:true})
  useEffect(()=>setMenuOpen(false),[pathname])
  useEffect(()=>{const close=event=>event.key==='Escape'&&setMenuOpen(false);window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[])
  return <header className="header"><Link className="logo-link" to="/"><Logo/></Link><nav aria-label="Main navigation">{nav.map((n,i)=><Link key={n} to={paths[i]}>{n}</Link>)}</nav><div className="header-actions"><label className="sr-only" htmlFor="lang">{t('language')}</label><select className="header-language" id="lang" value={lang} onChange={e=>setLang(e.target.value)}><option value="en">EN</option><option value="de">DE</option><option value="hy">HY</option></select><Link className="button small" to="/booking">{t('book')}</Link><button type="button" className={menuOpen?'menu-toggle open':'menu-toggle'} aria-label={t(menuOpen?'menuClose':'menuOpen')} aria-expanded={menuOpen} aria-controls="mobile-menu" onClick={()=>setMenuOpen(open=>!open)}><span/><span/><span/></button></div>{menuOpen&&<><button type="button" className="menu-scrim" aria-label={t('menuClose')} onClick={()=>setMenuOpen(false)}/><aside className="mobile-menu" id="mobile-menu" role="dialog" aria-modal="true" aria-label={t('menuTitle')}><p>{t('menuTitle')}</p><nav aria-label={t('menuTitle')}>{nav.map((n,i)=><Link key={n} to={paths[i]}><span>0{i+1}</span>{n}<i>↗</i></Link>)}</nav><div className="mobile-language" aria-label={t('language')}>{['en','de','hy'].map(code=><button type="button" className={lang===code?'active':''} key={code} onClick={()=>setLang(code)}>{code.toUpperCase()}</button>)}</div><Link className="button" to="/booking">{t('book')}<span>→</span></Link></aside></>}</header>
}

function Art({ variant='arch' }) { return <div className={`art ${variant}`} aria-hidden="true"><span/><i/><b/></div> }

function HeroPoster({ copy: t, lang }) {
  return <section className="hero hero-poster" aria-labelledby="home-title">
    <div className="hero-poster-visual">
      <picture className="hero-poster-picture">
        <source media="(max-width: 700px), (max-height: 600px) and (max-width: 1000px)" srcSet={`${import.meta.env.BASE_URL}hero-mobile.png`}/>
        <img className="hero-poster-image" src={`${import.meta.env.BASE_URL}hero-background.png`} alt="" aria-hidden="true"/>
      </picture>
      <div className="hero-poster-questions" aria-hidden="true">{t.reflectionQuestions.slice(0,3).map((question,index)=><span className={`floating-question poster-question-${index+1}`} key={question}>{question}</span>)}</div>
    </div>
    <div className={`hero-poster-heading lang-${lang}`}>
      <p className="hero-wordmark">{t.heroBrand}</p>
      <h1 id="home-title"><span>{t.titleA}</span><em>{t.titleB}</em></h1>
    </div>
    <div className="hero-poster-content">
      <p className="eyebrow">{t.eyebrow}</p>
      <p className="hero-poster-intro">{t.intro}</p>
      <div className="button-row"><Link className="button" to="/booking">{t.book}<span>→</span></Link><Link className="text-link" to="/sessions">{t.explore}<span>→</span></Link></div>
      <div className="trust-row">{t.trust.map(item=><span key={item}>{item}</span>)}</div>
    </div>
  </section>
}

const bookingFlowCopy = {
  en: {
    serviceTitle:'How would you like to begin?', serviceIntro:'Choose one path. Each has its own short questionnaire.',
    services:[['private','Private session','One-to-one support, usually available.'],['couple','Couple session','A shared session for two adults, usually available.'],['group','Monthly group session','The next date and location will be announced soon.']],
    privateQuestions:[
      ['format','Where would you prefer to meet?',[['online','Online'],['heidelberg','Near Heidelberg'],['yerevan','Yerevan · coming soon'],['flexible','I am flexible']]],
      ['duration','What session length would you prefer?',[['60','60 minutes'],['90','90 minutes'],['120','120 minutes'],['unsure','I am not sure yet']]],
      ['cadence','What kind of start are you considering?',[['single','One session'],['recurring','Recurring sessions'],['unsure','I would like guidance']]],
      ['language','Preferred language',[['en','English'],['de','German'],['hy','Armenian'],['flexible','No preference']]],
    ],
    coupleQuestions:[
      ['format','Where would you both prefer to meet?',[['online','Online'],['heidelberg','Near Heidelberg'],['yerevan','Yerevan · coming soon'],['flexible','We are flexible']]],
      ['duration','What session length would you prefer?',[['75','75 minutes'],['90','90 minutes'],['120','120 minutes'],['unsure','We are not sure yet']]],
      ['focus','What shared starting point fits best?',[['communication','Communication'],['transition','A transition or decision'],['reconnection','Reconnection'],['other','Another shared goal']]],
      ['consent','Do both adults know about and agree to this request?',[['yes','Yes, both of us agree'],['discuss','Not yet — we will discuss it first']]],
    ],
    groupQuestions:[
      ['language','Preferred group language',[['hy','Armenian'],['en','English'],['de','German'],['flexible','No preference']]],
      ['format','Which group format interests you most?',[['circle','Guided discussion circle'],['workshop','Practical workshop'],['activity','Shared activity'],['any','Any format']]],
    ],
    questionHint:'Choose the answer that is closest. Pricing is intentionally not shown yet.', back:'Back', next:'Next',
    calendarTitle:'Choose a preferred time', calendarIntro:'Select one preferred time and, if useful, one backup. Sarah confirms the final appointment after reviewing your request.', calendarPreview:'Preview availability — Sarah’s live calendar is not connected yet. These times are for testing and are not being held.', calendarLive:'Times are shown in the Europe/Berlin time zone. A selected time is requested, not confirmed.', calendarLoading:'Loading available times…', calendarEmpty:'No times are available right now. Go back to change your preferences or contact House of Hoki.', calendarChoice:'Choose at least one time to continue.', primary:'Preferred', backup:'Backup', timeZone:'Europe/Berlin time',
    contactTitle:'Where should Sarah reply?', contactIntro:'Your request is reviewed before a booking is confirmed. A calendar invitation is sent only after Sarah approves it.', name:'Name', email:'Email', emailError:'Enter a complete email address, for example name@example.com.', phone:'Phone or WhatsApp · optional', privacy:'I agree that House of Hoki may use these details to review and reply to this booking request.', review:'Review request',
    reviewTitle:'Review your request', reviewIntro:'The selected time is still a request. No price is calculated yet, and Sarah makes the final confirmation.', service:'Service', details:'Preferences', requestedTime:'Requested time', submit:'Send request for approval', submitting:'Sending…', edit:'Edit answers', calendarSubmitError:'Live availability must be connected before this request can be sent.',
    pending:'Request received', pendingText:'Sarah will review the request before confirming it. The n8n workflow will send the approved booking to the calendar and then email the invitation.', preview:'Booking automation is being prepared', previewText:'The secure Cloudflare-to-n8n endpoint is not active yet, so no personal details were sent. You can contact House of Hoki by email in the meantime.', error:'The request could not be sent. Please try again or contact us by email.',
    groupSoon:'Next monthly group session', groupSoonText:'Date and location coming soon.', memberTitle:'Continue with the community', memberText:'Membership and the summer weekend program will be introduced after the final benefits and prices are confirmed.', emailAction:'Email info@houseofhoki.com'
  },
  de: {
    serviceTitle:'Wie möchtest du beginnen?', serviceIntro:'Wähle einen Weg. Für jeden gibt es einen eigenen kurzen Fragebogen.',
    services:[['private','Private Sitzung','Individuelle Begleitung, in der Regel verfügbar.'],['couple','Paarsitzung','Eine gemeinsame Sitzung für zwei Erwachsene, in der Regel verfügbar.'],['group','Monatliche Gruppensitzung','Der nächste Termin und Ort werden bald bekannt gegeben.']],
    privateQuestions:[['format','Wo möchtest du dich treffen?',[['online','Online'],['heidelberg','Bei Heidelberg'],['yerevan','Jerewan · demnächst'],['flexible','Ich bin flexibel']]],['duration','Welche Sitzungsdauer bevorzugst du?',[['60','60 Minuten'],['90','90 Minuten'],['120','120 Minuten'],['unsure','Noch nicht sicher']]],['cadence','Welchen Start erwägst du?',[['single','Eine Sitzung'],['recurring','Regelmäßige Sitzungen'],['unsure','Ich wünsche mir Orientierung']]],['language','Bevorzugte Sprache',[['en','Englisch'],['de','Deutsch'],['hy','Armenisch'],['flexible','Keine Präferenz']]]],
    coupleQuestions:[['format','Wo möchtet ihr euch treffen?',[['online','Online'],['heidelberg','Bei Heidelberg'],['yerevan','Jerewan · demnächst'],['flexible','Wir sind flexibel']]],['duration','Welche Sitzungsdauer bevorzugt ihr?',[['75','75 Minuten'],['90','90 Minuten'],['120','120 Minuten'],['unsure','Noch nicht sicher']]],['focus','Welcher gemeinsame Ausgangspunkt passt am besten?',[['communication','Kommunikation'],['transition','Veränderung oder Entscheidung'],['reconnection','Wiederannäherung'],['other','Ein anderes gemeinsames Ziel']]],['consent','Wissen beide Erwachsenen von dieser Anfrage und stimmen ihr zu?',[['yes','Ja, wir stimmen beide zu'],['discuss','Noch nicht — wir besprechen es zuerst']]]],
    groupQuestions:[['language','Bevorzugte Gruppensprache',[['hy','Armenisch'],['en','Englisch'],['de','Deutsch'],['flexible','Keine Präferenz']]],['format','Welches Gruppenformat interessiert dich?',[['circle','Moderierter Gesprächskreis'],['workshop','Praktischer Workshop'],['activity','Gemeinsame Aktivität'],['any','Alle Formate']]]],
    questionHint:'Wähle die passendste Antwort. Preise werden bewusst noch nicht angezeigt.', back:'Zurück', next:'Weiter', calendarTitle:'Wähle einen Wunschtermin', calendarIntro:'Wähle einen bevorzugten Termin und optional eine Alternative. Sarah bestätigt den endgültigen Termin nach Prüfung der Anfrage.', calendarPreview:'Vorschau der Verfügbarkeit — Sarahs Live-Kalender ist noch nicht verbunden. Diese Zeiten dienen nur zum Testen und werden nicht reserviert.', calendarLive:'Die Zeiten werden in der Zeitzone Europe/Berlin angezeigt. Eine ausgewählte Zeit ist angefragt, nicht bestätigt.', calendarLoading:'Verfügbare Zeiten werden geladen …', calendarEmpty:'Zurzeit sind keine Termine verfügbar. Gehe zurück, ändere deine Angaben oder kontaktiere House of Hoki.', calendarChoice:'Wähle mindestens einen Termin aus.', primary:'Wunschtermin', backup:'Alternative', timeZone:'Zeit in Europe/Berlin', contactTitle:'Wie darf Sarah antworten?', contactIntro:'Sarah prüft jede Anfrage vor der Bestätigung. Erst nach ihrer Freigabe wird eine Kalendereinladung versendet.', name:'Name', email:'E-Mail', emailError:'Gib eine vollständige E-Mail-Adresse ein, zum Beispiel name@example.com.', phone:'Telefon oder WhatsApp · optional', privacy:'Ich bin einverstanden, dass House of Hoki diese Angaben zur Prüfung und Beantwortung meiner Anfrage verwendet.', review:'Anfrage prüfen', reviewTitle:'Anfrage überprüfen', reviewIntro:'Der gewählte Termin ist weiterhin eine Anfrage. Noch wird kein Preis berechnet; Sarah bestätigt endgültig.', service:'Leistung', details:'Präferenzen', requestedTime:'Angefragter Termin', submit:'Zur Bestätigung senden', submitting:'Wird gesendet …', edit:'Antworten ändern', calendarSubmitError:'Vor dem Senden muss die Live-Verfügbarkeit verbunden sein.', pending:'Anfrage eingegangen', pendingText:'Sarah prüft die Anfrage vor der Bestätigung. Der n8n-Ablauf überträgt die freigegebene Buchung anschließend in den Kalender und versendet die Einladung.', preview:'Buchungsautomatisierung wird vorbereitet', previewText:'Der sichere Cloudflare-zu-n8n-Endpunkt ist noch nicht aktiv. Es wurden keine persönlichen Daten übertragen. Du kannst House of Hoki vorerst per E-Mail kontaktieren.', error:'Die Anfrage konnte nicht gesendet werden. Bitte versuche es erneut oder schreibe uns per E-Mail.', groupSoon:'Nächste monatliche Gruppensitzung', groupSoonText:'Termin und Ort folgen.', memberTitle:'Mit der Community verbunden bleiben', memberText:'Mitgliedschaft und Sommerwochenende werden vorgestellt, sobald Leistungen und Preise bestätigt sind.', emailAction:'E-Mail an info@houseofhoki.com'
  },
  hy: {
    serviceTitle:'Ինչպե՞ս եք ցանկանում սկսել։', serviceIntro:'Ընտրեք տարբերակներից մեկը։ Յուրաքանչյուրն ունի իր կարճ հարցաշարը։',
    services:[['private','Անհատական հանդիպում','Անհատական աջակցություն՝ սովորաբար հասանելի։'],['couple','Զույգերի հանդիպում','Համատեղ հանդիպում երկու չափահասների համար՝ սովորաբար հասանելի։'],['group','Ամսական խմբային հանդիպում','Հաջորդ ամսաթիվն ու վայրը կհայտարարվեն շուտով։']],
    privateQuestions:[['format','Որտե՞ղ կցանկանայիք հանդիպել։',[['online','Առցանց'],['heidelberg','Հայդելբերգի մոտ'],['yerevan','Երևան · շուտով'],['flexible','Ճկուն եմ']]],['duration','Ի՞նչ տևողություն եք նախընտրում։',[['60','60 րոպե'],['90','90 րոպե'],['120','120 րոպե'],['unsure','Դեռ վստահ չեմ']]],['cadence','Ինչպիսի՞ սկիզբ եք դիտարկում։',[['single','Մեկ հանդիպում'],['recurring','Կրկնվող հանդիպումներ'],['unsure','Ուղղորդման կարիք ունեմ']]],['language','Նախընտրելի լեզու',[['en','Անգլերեն'],['de','Գերմաներեն'],['hy','Հայերեն'],['flexible','Նախընտրություն չկա']]]],
    coupleQuestions:[['format','Որտե՞ղ կցանկանայիք հանդիպել երկուսով։',[['online','Առցանց'],['heidelberg','Հայդելբերգի մոտ'],['yerevan','Երևան · շուտով'],['flexible','Ճկուն ենք']]],['duration','Ի՞նչ տևողություն եք նախընտրում։',[['75','75 րոպե'],['90','90 րոպե'],['120','120 րոպե'],['unsure','Դեռ վստահ չենք']]],['focus','Ո՞ր ընդհանուր նպատակը լավագույն մեկնարկն է։',[['communication','Հաղորդակցություն'],['transition','Փոփոխություն կամ որոշում'],['reconnection','Վերամերձեցում'],['other','Այլ ընդհանուր նպատակ']]],['consent','Երկու չափահասներն էլ գիտե՞ն և համաձա՞յն են այս հարցմանը։',[['yes','Այո, երկուսս էլ համաձայն ենք'],['discuss','Դեռ ոչ՝ նախ կքննարկենք']]]],
    groupQuestions:[['language','Խմբի նախընտրելի լեզու',[['hy','Հայերեն'],['en','Անգլերեն'],['de','Գերմաներեն'],['flexible','Նախընտրություն չկա']]],['format','Ո՞ր խմբային ձևաչափն է ձեզ հետաքրքրում։',[['circle','Ուղղորդվող քննարկում'],['workshop','Գործնական աշխատարան'],['activity','Համատեղ գործունեություն'],['any','Ցանկացած ձևաչափ']]]],
    questionHint:'Ընտրեք ամենամոտ պատասխանը։ Գները դեռ չեն ցուցադրվում։', back:'Հետ', next:'Հաջորդը', calendarTitle:'Ընտրեք նախընտրելի ժամ', calendarIntro:'Ընտրեք մեկ նախընտրելի ժամ և, ցանկության դեպքում, մեկ այլընտրանք։ Սառան վերջնականապես կհաստատի հանդիպումը հարցումը դիտարկելուց հետո։', calendarPreview:'Հասանելիության նախադիտում — Սառայի իրական օրացույցը դեռ միացված չէ։ Այս ժամերը միայն փորձարկման համար են և չեն ամրագրվում։', calendarLive:'Ժամերը ցուցադրվում են Europe/Berlin ժամային գոտով։ Ընտրված ժամը հարցում է, ոչ թե հաստատված ամրագրում։', calendarLoading:'Հասանելի ժամերը բեռնվում են…', calendarEmpty:'Այս պահին հասանելի ժամեր չկան։ Վերադարձեք, փոխեք նախընտրությունները կամ կապվեք House of Hoki-ի հետ։', calendarChoice:'Շարունակելու համար ընտրեք առնվազն մեկ ժամ։', primary:'Նախընտրելի', backup:'Այլընտրանք', timeZone:'Europe/Berlin ժամով', contactTitle:'Ինչպե՞ս Սառան կապվի ձեզ հետ։', contactIntro:'Սառան ստուգում է հարցումը նախքան հաստատումը։ Օրացույցի հրավերը ուղարկվում է միայն հաստատումից հետո։', name:'Անուն', email:'Էլ․ հասցե', emailError:'Մուտքագրեք ամբողջական էլ․ հասցե, օրինակ՝ name@example.com։', phone:'Հեռախոս կամ WhatsApp · ոչ պարտադիր', privacy:'Համաձայն եմ, որ House of Hoki-ն օգտագործի այս տվյալները հարցումը ստուգելու և պատասխանելու համար։', review:'Ստուգել հարցումը', reviewTitle:'Ստուգեք ձեր հարցումը', reviewIntro:'Ընտրված ժամը դեռ հարցում է։ Գին չի հաշվարկվում, և վերջնական հաստատումը տալիս է Սառան։', service:'Ծառայություն', details:'Նախընտրություններ', requestedTime:'Հարցված ժամ', submit:'Ուղարկել հաստատման', submitting:'Ուղարկվում է…', edit:'Փոխել պատասխանները', calendarSubmitError:'Ուղարկելուց առաջ պետք է միացված լինի իրական հասանելիության օրացույցը։', pending:'Հարցումը ստացվել է', pendingText:'Սառան կստուգի հարցումը։ Հաստատումից հետո n8n գործընթացը այն կավելացնի օրացույց և կուղարկի հրավեր։', preview:'Ամրագրման ավտոմատացումը պատրաստվում է', previewText:'Cloudflare-ից n8n անվտանգ կապը դեռ ակտիվ չէ, ուստի անձնական տվյալներ չեն ուղարկվել։ Առայժմ կարող եք գրել House of Hoki-ին։', error:'Հարցումը չհաջողվեց ուղարկել։ Փորձեք կրկին կամ գրեք էլ․ փոստով։', groupSoon:'Հաջորդ ամսական խմբային հանդիպումը', groupSoonText:'Ամսաթիվն ու վայրը՝ շուտով։', memberTitle:'Շարունակեք համայնքի հետ', memberText:'Անդամակցությունն ու ամառային հանգստյան ծրագիրը կներկայացվեն առավելություններն ու գները հաստատելուց հետո։', emailAction:'Գրել info@houseofhoki.com-ին'
  }
}

const BOOKING_TIME_ZONE='Europe/Berlin'
const bookingLocales={en:'en-GB',de:'de-DE',hy:'hy-AM'}
const twoDigits=value=>String(value).padStart(2,'0')
const dateKey=date=>`${date.getFullYear()}-${twoDigits(date.getMonth()+1)}-${twoDigits(date.getDate())}`
const addMinutes=(time,minutes)=>{const [hours,mins]=time.split(':').map(Number);const total=hours*60+mins+minutes;return `${twoDigits(Math.floor(total/60)%24)}:${twoDigits(total%60)}`}
const slotDuration=(service,answer)=>{const parsed=Number.parseInt(answer,10);return Number.isFinite(parsed)?parsed:service==='couple'?90:60}
function previewAvailability(service,durationAnswer){
  const times=service==='couple'?['17:00','18:30']:['09:30','12:00','16:30']
  const duration=slotDuration(service,durationAnswer)
  const days=[]
  const cursor=new Date()
  cursor.setHours(12,0,0,0)
  for(let offset=1;offset<=18&&days.length<6;offset+=1){
    const day=new Date(cursor)
    day.setDate(cursor.getDate()+offset)
    if([1,2,4,6].includes(day.getDay()))days.push(day)
  }
  return days.flatMap((day,dayIndex)=>times.slice(0,dayIndex%2===0?times.length:2).map(time=>({id:`preview-${service}-${dateKey(day)}-${time.replace(':','')}`,date:dateKey(day),start:time,end:addMinutes(time,duration),timezone:BOOKING_TIME_ZONE})))
}
const validSlot=slot=>slot&&typeof slot.id==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(slot.date)&&/^\d{2}:\d{2}$/.test(slot.start)&&/^\d{2}:\d{2}$/.test(slot.end)
const formatSlotDate=(date,lang)=>new Intl.DateTimeFormat(bookingLocales[lang]||bookingLocales.en,{weekday:'short',day:'numeric',month:'short'}).format(new Date(`${date}T12:00:00`))
const formatSlotSummary=(slot,lang)=>`${formatSlotDate(slot.date,lang)} · ${slot.start}–${slot.end} · ${slot.timezone||BOOKING_TIME_ZONE}`

function BookingPlanner({ lang, initialService='' }) {
  const c=bookingFlowCopy[lang]||bookingFlowCopy.en
  const validInitial=c.services.some(([id])=>id===initialService)?initialService:''
  const [service,setService]=useState(validInitial)
  const [phase,setPhase]=useState(validInitial?'questions':'service')
  const [questionIndex,setQuestionIndex]=useState(0)
  const [answers,setAnswers]=useState({})
  const [contact,setContact]=useState({name:'',email:'',phone:'',consent:false})
  const [status,setStatus]=useState('idle')
  const [availability,setAvailability]=useState({status:'idle',source:'',slots:[]})
  const [selectedSlotIds,setSelectedSlotIds]=useState([])
  const questions=service==='private'?c.privateQuestions:service==='couple'?c.coupleQuestions:c.groupQuestions
  const selectedService=c.services.find(([id])=>id===service)
  const question=questions[questionIndex]
  const timedService=service==='private'||service==='couple'
  const emailValid=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contact.email.trim())
  const selectedSlots=selectedSlotIds.map(id=>availability.slots.find(slot=>slot.id===id)).filter(Boolean)
  const slotsByDate=availability.slots.reduce((groups,slot)=>({...groups,[slot.date]:[...(groups[slot.date]||[]),slot]}),{})
  const chooseService=id=>{setService(id);setAnswers({});setQuestionIndex(0);setSelectedSlotIds([]);setAvailability({status:'idle',source:'',slots:[]});setPhase('questions');setStatus('idle')}
  useEffect(()=>{
    if(phase!=='calendar'||!timedService)return undefined
    const endpoint=import.meta.env.VITE_AVAILABILITY_ENDPOINT
    const controller=new AbortController()
    if(!endpoint){const slots=previewAvailability(service,answers.duration);setAvailability({status:'ready',source:'preview',slots});setSelectedSlotIds(current=>current.filter(id=>slots.some(slot=>slot.id===id)));return ()=>controller.abort()}
    setAvailability({status:'loading',source:'live',slots:[]})
    const url=new URL(endpoint,window.location.origin)
    url.searchParams.set('service',service)
    url.searchParams.set('format',answers.format||'flexible')
    url.searchParams.set('duration',answers.duration||'unsure')
    url.searchParams.set('locale',lang)
    url.searchParams.set('timezone',BOOKING_TIME_ZONE)
    fetch(url,{signal:controller.signal,headers:{Accept:'application/json'}}).then(response=>{if(!response.ok)throw new Error('availability request failed');return response.json()}).then(data=>{
      const slots=(Array.isArray(data)?data:data.slots||[]).filter(validSlot).slice(0,40).map(slot=>({...slot,timezone:slot.timezone||data.timezone||BOOKING_TIME_ZONE}))
      setAvailability({status:'ready',source:'live',slots})
      setSelectedSlotIds(current=>current.filter(id=>slots.some(slot=>slot.id===id)))
    }).catch(error=>{if(error.name!=='AbortError'){setAvailability({status:'error',source:'live',slots:[]});setSelectedSlotIds([])}})
    return ()=>controller.abort()
  },[phase,timedService,service,answers.format,answers.duration,lang])
  const toggleSlot=id=>setSelectedSlotIds(current=>current.includes(id)?current.filter(slotId=>slotId!==id):current.length<2?[...current,id]:[current[0],id])
  const goBack=()=>{
    if(phase==='questions'&&questionIndex>0)setQuestionIndex(index=>index-1)
    else if(phase==='questions')setPhase('service')
    else if(phase==='calendar'){setQuestionIndex(questions.length-1);setPhase('questions')}
    else if(phase==='contact'){if(timedService)setPhase('calendar');else setPhase('questions')}
    else if(phase==='review'){setStatus('idle');setPhase('contact')}
  }
  const advance=()=>{
    if(phase==='questions'&&questionIndex<questions.length-1)setQuestionIndex(index=>index+1)
    else if(phase==='questions')setPhase(timedService?'calendar':'contact')
    else if(phase==='calendar')setPhase('contact')
    else if(phase==='contact')setPhase('review')
  }
  const submit=async()=>{
    const endpoint=import.meta.env.VITE_BOOKING_ENDPOINT
    if(!endpoint){setStatus('preview');return}
    if(timedService&&availability.source!=='live'){setStatus('calendar-error');return}
    setStatus('submitting')
    try{
      const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({schemaVersion:'hoki-booking-request-v2',service,answers,requestedSlots:selectedSlots.map(({id,date,start,end,timezone})=>({id,date,start,end,timezone})),availabilitySource:timedService?availability.source:'not_applicable',contact:{name:contact.name,email:contact.email,phone:contact.phone},locale:lang,consent:true,source:'website'})})
      if(!response.ok)throw new Error('booking request failed')
      setStatus('sent')
    }catch{setStatus('error')}
  }
  if(status==='sent'||status==='preview')return <section className="modal booking-planner confirmation-panel" aria-live="polite"><div className="ai-orb" aria-hidden="true">{status==='sent'?'✓':'○'}</div><p className="question-domain">House of Hoki</p><h2>{status==='sent'?c.pending:c.preview}</h2><p>{status==='sent'?c.pendingText:c.previewText}</p><div className="post-booking-grid"><article><span>{c.groupSoon}</span><strong>{c.groupSoonText}</strong></article><article><span>{c.memberTitle}</span><strong>{c.memberText}</strong></article></div>{status==='preview'&&<a className="button" href="mailto:info@houseofhoki.com?subject=Booking%20request">{c.emailAction}<span>→</span></a>}</section>
  const totalSteps=timedService?4:3
  const progress=phase==='service'?12:phase==='questions'?20+((questionIndex+1)/questions.length)*34:phase==='calendar'?68:phase==='contact'?84:95
  return <section className="modal booking-planner" aria-labelledby="booking-flow-title"><div className="estimate-progress" aria-hidden="true"><span style={{width:`${progress}%`}}/></div>
    {phase==='service'&&<><p className="question-domain">01 · 04</p><h2 id="booking-flow-title">{c.serviceTitle}</h2><p>{c.serviceIntro}</p><div className="service-options">{c.services.map(([id,title,description],index)=><button type="button" key={id} onClick={()=>chooseService(id)}><b>0{index+1}</b><span><strong>{title}</strong><small>{description}</small></span><i>→</i></button>)}</div></>}
    {phase==='questions'&&question&&<><p className="question-domain">{selectedService?.[1]} · {questionIndex+1}/{questions.length}</p><h2 id="booking-flow-title">{question[1]}</h2><p>{c.questionHint}</p><div className="option-grid booking-options">{question[2].map(([value,label])=><button type="button" key={value} className={answers[question[0]]===value?'option selected':'option'} onClick={()=>setAnswers({...answers,[question[0]]:value})}><span>{label}</span><i>{answers[question[0]]===value?'✓':'→'}</i></button>)}</div></>}
    {phase==='calendar'&&<><p className="question-domain">02 · 04</p><h2 id="booking-flow-title">{c.calendarTitle}</h2><p>{c.calendarIntro}</p><div className={`availability-note ${availability.source}`} role="status">{availability.source==='preview'?c.calendarPreview:c.calendarLive}</div>{availability.status==='loading'&&<p className="calendar-status" aria-live="polite">{c.calendarLoading}</p>}{availability.status==='error'&&<p className="form-error" role="alert">{c.calendarEmpty}</p>}{availability.status==='ready'&&!availability.slots.length&&<p className="calendar-status">{c.calendarEmpty}</p>}<div className="calendar-grid">{Object.entries(slotsByDate).map(([date,slots])=><article className="calendar-day" key={date}><h3>{formatSlotDate(date,lang)}</h3><span>{c.timeZone}</span><div>{slots.map(slot=>{const selectedIndex=selectedSlotIds.indexOf(slot.id);return <button type="button" key={slot.id} className={selectedIndex>=0?'selected':''} aria-pressed={selectedIndex>=0} onClick={()=>toggleSlot(slot.id)}><strong>{slot.start}</strong><small>{selectedIndex===0?c.primary:selectedIndex===1?c.backup:`${slot.start}–${slot.end}`}</small></button>})}</div></article>)}</div>{availability.status==='ready'&&availability.slots.length>0&&selectedSlots.length===0&&<p className="calendar-guidance">{c.calendarChoice}</p>}</>}
    {phase==='contact'&&<><p className="question-domain">{twoDigits(timedService?3:2)} · {twoDigits(totalSteps)}</p><h2 id="booking-flow-title">{c.contactTitle}</h2><p>{c.contactIntro}</p><div className="contact-fields"><label><span>{c.name}</span><input autoComplete="name" maxLength="100" value={contact.name} onChange={event=>setContact({...contact,name:event.target.value})}/></label><label><span>{c.email}</span><input type="email" autoComplete="email" maxLength="254" aria-invalid={contact.email.length>0&&!emailValid} aria-describedby={contact.email.length>0&&!emailValid?'booking-email-error':undefined} value={contact.email} onChange={event=>setContact({...contact,email:event.target.value})}/>{contact.email.length>0&&!emailValid&&<small id="booking-email-error" className="field-error">{c.emailError}</small>}</label><label><span>{c.phone}</span><input type="tel" autoComplete="tel" maxLength="50" value={contact.phone} onChange={event=>setContact({...contact,phone:event.target.value})}/></label><label className="consent-field"><input type="checkbox" checked={contact.consent} onChange={event=>setContact({...contact,consent:event.target.checked})}/><span>{c.privacy}</span></label></div></>}
    {phase==='review'&&<><p className="question-domain">{twoDigits(totalSteps)} · {twoDigits(totalSteps)}</p><h2 id="booking-flow-title">{c.reviewTitle}</h2><p>{c.reviewIntro}</p><div className="request-review"><span>{c.service}</span><strong>{selectedService?.[1]}</strong><span>{c.details}</span><ul>{questions.map(([id,prompt,options])=><li key={id}><b>{prompt}</b><span>{options.find(([value])=>value===answers[id])?.[1]}</span></li>)}</ul>{timedService&&<><span>{c.requestedTime}</span><ul className="requested-slots">{selectedSlots.map((slot,index)=><li key={slot.id}><b>{index===0?c.primary:c.backup}</b><span>{formatSlotSummary(slot,lang)}</span></li>)}</ul></>}<span>{c.email}</span><strong>{contact.email}</strong></div>{status==='calendar-error'&&<p className="form-error" role="alert">{c.calendarSubmitError}</p>}{status==='error'&&<p className="form-error" role="alert">{c.error}</p>}</>}
    <div className="modal-actions">{phase!=='service'&&<button type="button" className="text-button" disabled={status==='submitting'} onClick={goBack}>{phase==='review'?c.edit:c.back}</button>}{phase==='questions'&&<button type="button" className="button" disabled={!answers[question?.[0]]} onClick={advance}>{c.next}<span>→</span></button>}{phase==='calendar'&&<button type="button" className="button" disabled={!selectedSlots.length} onClick={advance}>{c.next}<span>→</span></button>}{phase==='contact'&&<button type="button" className="button" disabled={!contact.name.trim()||!emailValid||!contact.consent} onClick={advance}>{c.review}<span>→</span></button>}{phase==='review'&&<button type="button" className="button" disabled={status==='submitting'} onClick={submit}>{status==='submitting'?c.submitting:c.submit}<span>→</span></button>}</div>
  </section>
}

function HomePage({ lang }) {
  const [openFaq,setOpenFaq] = useState(0)
  const t = copy[lang]
  return <main>
      <HeroPoster copy={t} lang={lang}/>

      <section className="reflection-section" aria-labelledby="reflection-title"><div className="reflection-heading"><p className="eyebrow">{t.reflectionKicker}</p><h2 id="reflection-title">{t.reflectionTitle}</h2><p>{t.reflectionIntro}</p></div><div className="question-cloud">{t.reflectionQuestions.map((question,index)=><Link className={`question-card card-${index+1}`} to="/booking" key={question}><span>{String(index+1).padStart(2,'0')}</span><strong>{question}</strong><i aria-hidden="true">↗</i></Link>)}</div></section>

      <section className="section intro-section"><div className="section-heading"><p className="eyebrow">{t.sectionKicker}</p><h2>{t.sectionTitle}</h2><p>{t.sectionIntro}</p></div><div className="service-grid"><article className="service-card"><div className="card-top"><span>01</span><Art variant="orb"/></div><h3>{t.privateTitle}</h3><p>{t.privateText}</p><div className="availability"><span>{t.availability}</span><strong>{t.usuallyAvailable}</strong></div><Link className="card-link" to="/booking?service=private">{t.estimate}<span>↗</span></Link></article><article className="service-card inverse"><div className="card-top"><span>02</span><Art variant="rings"/></div><h3>{t.coupleTitle}</h3><p>{t.coupleText}</p><div className="availability"><span>{t.availability}</span><strong>{t.usuallyAvailable}</strong></div><Link className="card-link" to="/booking?service=couple">{t.estimate}<span>↗</span></Link></article><article className="service-card group-card"><div className="card-top"><span>03</span><Art variant="flow"/></div><h3>{t.groupTitle}</h3><p>{t.groupText}</p><div className="availability"><span>{t.availability}</span><strong>{t.monthlySoon}</strong></div><Link className="card-link" to="/sessions/group-session">{t.seeActivities}<span>↗</span></Link></article></div></section>

      <section className="program-section"><div className="section-heading light"><p className="eyebrow">{t.programsKicker}</p><h2>{t.programsTitle}</h2></div><div className="program-list">{programs.map((p,i)=><article className="program" key={p.path}><div className={`program-mark ${p.className}`}>{p.mark}</div><div><span>{t.statuses[i]}</span><h3>{p.name}</h3><p>{i===0?t.commonText:t.youthText}</p></div><Link to={p.path} aria-label={`${i===0?t.apply:t.interest}: ${p.name}`}>{i===0?t.apply:t.interest}<span>→</span></Link></article>)}</div></section>

      <section className="section process" id="resources"><div className="section-heading"><p className="eyebrow">{t.processKicker}</p><h2>{t.processTitle}</h2></div><div className="steps">{t.steps.map(([n,title,desc])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></section>

      <section className="quote-section"><Art variant="flow"/><blockquote>{t.quote}</blockquote></section>

      <section className="section locations" id="about"><div className="section-heading"><p className="eyebrow">House of Hoki</p><h2>{t.locationTitle}</h2></div><div className="location-grid"><article><span>DE</span><h3>{t.heidelberg}</h3><p>{t.locationDetails[0]}</p></article><article><span>AM</span><h3>{t.yerevan}</h3><p>{t.locationDetails[1]}</p></article><article><span>∞</span><h3>{t.online}</h3><p>{t.locationDetails[2]}</p></article></div></section>

      <section className="section faq-section"><div className="section-heading"><p className="eyebrow">FAQ</p><h2>{t.faqTitle}</h2></div><div className="faq-list">{t.faq.map(([q,a],i)=><article className={openFaq===i?'faq open':'faq'} key={q}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)} aria-expanded={openFaq===i}><span>{String(i+1).padStart(2,'0')}</span><strong>{q}</strong><i>{openFaq===i?'−':'+'}</i></button>{openFaq===i&&<p>{a}</p>}</article>)}</div></section>

      <section className="cta"><p className="eyebrow">{t.ctaKicker}</p><h2>{t.titleA}<br/>{t.titleB}</h2><div className="button-row"><Link className="button pale" to="/booking">{t.book}<span>→</span></Link><Link className="text-link pale" to="/orientation-call">{t.orient}<span>↗</span></Link></div></section>
    </main>
}

const routePages = { en: {
  '/sessions/private-session': { kicker:'Private sessions', title:'A focused space for you.', intro:'A one-to-one session shaped around your goals, preferred format and pace.', facts:[['Format','Online · Heidelberg · Yerevan soon'],['Availability','Usually available'],['Next step','Private questionnaire + Sarah’s approval']], action:'Start the private questionnaire', service:'private' },
  '/sessions/couple-session': { kicker:'Couple sessions', title:'A shared space for two.', intro:'A session for two adults who want to explore communication, a transition or reconnection together.', facts:[['Format','Online · Heidelberg · Yerevan soon'],['Availability','Usually available'],['Next step','Couple questionnaire + Sarah’s approval']], action:'Start the couple questionnaire', service:'couple' },
  '/sessions/group-session': { kicker:'Monthly group sessions', title:'Meet through meaningful conversation.', intro:'A facilitated group format planned once a month for reflection, connection and practical growth.', facts:[['Rhythm','Once a month'],['Next date','Coming soon'],['Location','Coming soon']], action:'Register group interest', service:'group' },
  '/activities/discussion-circle': { kicker:'Group activity', title:'Meet through meaningful conversation.', intro:'A facilitated discussion circle designed as the first Common Club pilot activity.', facts:[['Location','Yerevan'],['Language','Armenian · English'],['Availability','Pilot dates coming soon']], action:'Register interest' },
  '/programs/common-club': { kicker:'Common Club · Armenia', title:'Come together around what we share.', intro:'A free community pilot for people aged 18–45, owned with an independent program partner and facilitated with Sarah.', facts:[['Age','18–45'],['First format','Discussion circle'],['Admission','Questionnaire + approval']], action:'Apply to the pilot' },
  '/programs/hoki-youth-germany': { kicker:'Hoki for Youth · Germany', title:'A shared language for growing forward.', intro:'A developing well-being program for young people, sharing one identity with Hoki for Youth Armenia.', facts:[['Age','16–29'],['Region','Near Heidelberg'],['Status','Registering interest']], action:'Register interest' },
  '/programs/hoki-youth-armenia': { kicker:'Hoki for Youth · Armenia', title:'Local roots. Shared possibility.', intro:'A developing multilingual well-being program for young people in Armenia.', facts:[['Age','16–29'],['Region','Yerevan'],['Status','Registering interest']], action:'Register interest' },
}, de: {
  '/sessions/private-session':{kicker:'Private Sitzungen',title:'Ein fokussierter Raum für dich.',intro:'Eine persönliche Sitzung, abgestimmt auf deine Ziele, dein Format und dein Tempo.',facts:[['Format','Online · Heidelberg · Jerewan demnächst'],['Verfügbarkeit','In der Regel verfügbar'],['Nächster Schritt','Privater Fragebogen + Sarahs Freigabe']],action:'Privaten Fragebogen starten',service:'private'},
  '/sessions/couple-session':{kicker:'Paarsitzungen',title:'Ein gemeinsamer Raum für zwei.',intro:'Eine Sitzung für zwei Erwachsene rund um Kommunikation, Veränderung oder Wiederannäherung.',facts:[['Format','Online · Heidelberg · Jerewan demnächst'],['Verfügbarkeit','In der Regel verfügbar'],['Nächster Schritt','Paarfragebogen + Sarahs Freigabe']],action:'Paarfragebogen starten',service:'couple'},
  '/sessions/group-session':{kicker:'Monatliche Gruppensitzungen',title:'Begegnung durch bedeutungsvolle Gespräche.',intro:'Ein monatlich geplantes, moderiertes Gruppenformat für Reflexion, Verbindung und praktisches Wachstum.',facts:[['Rhythmus','Einmal im Monat'],['Nächster Termin','Demnächst'],['Ort','Demnächst']],action:'Gruppeninteresse anmelden',service:'group'},
  '/activities/discussion-circle':{kicker:'Gruppenaktivität',title:'Begegnung durch bedeutungsvolle Gespräche.',intro:'Ein moderierter Gesprächskreis als erste Pilotaktivität des Common Club.',facts:[['Ort','Jerewan'],['Sprache','Armenisch · Englisch'],['Verfügbarkeit','Pilottermine folgen']],action:'Interesse anmelden'},
  '/programs/common-club':{kicker:'Common Club · Armenien',title:'Zusammenkommen durch das, was uns verbindet.',intro:'Ein kostenloses Community-Pilotprojekt für 18- bis 45-Jährige, gemeinsam mit einem unabhängigen Programmpartner und Sarah als Begleiterin.',facts:[['Alter','18–45'],['Erstes Format','Gesprächskreis'],['Aufnahme','Fragebogen + Bestätigung']],action:'Für Pilot bewerben'},
  '/programs/hoki-youth-germany':{kicker:'Hoki for Youth · Deutschland',title:'Eine gemeinsame Sprache fürs Weiterwachsen.',intro:'Ein entstehendes Wohlfühlprogramm für junge Menschen mit gemeinsamer Identität in Deutschland und Armenien.',facts:[['Alter','16–29'],['Region','Bei Heidelberg'],['Status','Interessenliste']],action:'Interesse anmelden'},
  '/programs/hoki-youth-armenia':{kicker:'Hoki for Youth · Armenien',title:'Lokale Wurzeln. Gemeinsame Möglichkeiten.',intro:'Ein entstehendes mehrsprachiges Wohlfühlprogramm für junge Menschen in Armenien.',facts:[['Alter','16–29'],['Region','Jerewan'],['Status','Interessenliste']],action:'Interesse anmelden'}
}, hy: {
  '/sessions/private-session':{kicker:'Անհատական հանդիպումներ',title:'Կենտրոնացված տարածք ձեզ համար։',intro:'Անհատական հանդիպում՝ ձեր նպատակներին, նախընտրելի ձևաչափին և տեմպին համապատասխան։',facts:[['Ձևաչափ','Առցանց · Հայդելբերգ · Երևան՝ շուտով'],['Հասանելիություն','Սովորաբար հասանելի'],['Հաջորդ քայլ','Անհատական հարցաշար + Սառայի հաստատում']],action:'Սկսել անհատական հարցաշարը',service:'private'},
  '/sessions/couple-session':{kicker:'Զույգերի հանդիպումներ',title:'Համատեղ տարածք երկուսի համար։',intro:'Հանդիպում երկու չափահասների համար՝ հաղորդակցության, փոփոխության կամ վերամերձեցման շուրջ։',facts:[['Ձևաչափ','Առցանց · Հայդելբերգ · Երևան՝ շուտով'],['Հասանելիություն','Սովորաբար հասանելի'],['Հաջորդ քայլ','Զույգերի հարցաշար + Սառայի հաստատում']],action:'Սկսել զույգերի հարցաշարը',service:'couple'},
  '/sessions/group-session':{kicker:'Ամսական խմբային հանդիպումներ',title:'Միավորվենք իմաստալից զրույցի միջոցով։',intro:'Ամսական ուղղորդվող խմբային ձևաչափ՝ մտորելու, կապվելու և գործնական աճի համար։',facts:[['Հաճախականություն','Ամիսը մեկ անգամ'],['Հաջորդ ամսաթիվ','Շուտով'],['Վայր','Շուտով']],action:'Գրանցել խմբային հետաքրքրությունը',service:'group'},
  '/activities/discussion-circle':{kicker:'Խմբային միջոցառում',title:'Ծանոթացեք իմաստալից զրույցի միջոցով։',intro:'Ուղղորդվող քննարկման շրջան՝ որպես Common Club-ի առաջին փորձնական միջոցառում։',facts:[['Վայր','Երևան'],['Լեզու','Հայերեն · Անգլերեն'],['Հասանելիություն','Ամսաթվերը՝ շուտով']],action:'Գրանցել հետաքրքրությունը'},
  '/programs/common-club':{kicker:'Common Club · Հայաստան',title:'Միավորվենք մեր ընդհանրությունների շուրջ։',intro:'Անվճար համայնքային փորձնական ծրագիր 18–45 տարեկանների համար՝ անկախ գործընկերոջ և Սառայի աջակցությամբ։',facts:[['Տարիք','18–45'],['Առաջին ձևաչափ','Քննարկման շրջան'],['Ընդունելություն','Հարցաշար + հաստատում']],action:'Դիմել փորձնական ծրագրին'},
  '/programs/hoki-youth-germany':{kicker:'Hoki for Youth · Գերմանիա',title:'Ընդհանուր լեզու՝ առաջ աճելու համար։',intro:'Երիտասարդների բարեկեցության զարգացող ծրագիր՝ նույն ինքնությամբ Գերմանիայում և Հայաստանում։',facts:[['Տարիք','16–29'],['Տարածաշրջան','Հայդելբերգի մոտ'],['Կարգավիճակ','Հետաքրքրության գրանցում']],action:'Գրանցել հետաքրքրությունը'},
  '/programs/hoki-youth-armenia':{kicker:'Hoki for Youth · Հայաստան',title:'Տեղական արմատներ։ Ընդհանուր հնարավորություններ։',intro:'Երիտասարդների համար զարգացող բազմալեզու բարեկեցության ծրագիր Հայաստանում։',facts:[['Տարիք','16–29'],['Տարածաշրջան','Երևան'],['Կարգավիճակ','Հետաքրքրության գրանցում']],action:'Գրանցել հետաքրքրությունը'}
}}

function DetailPage({ page }) {
  const {t}=useTranslation()
  return <main><section className="detail-hero"><div><p className="eyebrow">{page.kicker}</p><h1>{page.title}</h1><p className="lead">{page.intro}</p><div className="button-row"><Link className="button" to={page.service?`/booking?service=${page.service}`:'/booking'}>{page.action}<span>→</span></Link><Link className="text-link" to="/orientation-call">{t('details.orientation')}<span>↗</span></Link></div></div><Art variant="orb"/></section><section className="detail-facts">{page.facts.map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="detail-body"><p className="eyebrow">{t('details.expect')}</p><h2>{t('details.clear')}</h2><div className="detail-columns"><p>{t('details.expectA')}</p><p>{t('details.expectB')}</p></div></section></main>
}

function ListingPage({ type }) {
  const {t}=useTranslation()
  const sessions = type==='sessions'
  return <main><section className="page-intro"><p className="eyebrow">House of Hoki</p><h1>{t(sessions?'listing.sessionsTitle':'listing.activitiesTitle')}</h1><p className="lead">{t(sessions?'listing.sessionsIntro':'listing.activitiesIntro')}</p></section><section className={sessions?'listing-grid three':'listing-grid'}>{sessions?<><Link className="listing-card blush" to="/sessions/private-session"><span>01</span><h2>{t('listing.private')}</h2><p>{t('listing.privateMeta')}</p><strong>{t('listing.explore')}</strong></Link><Link className="listing-card ice" to="/sessions/couple-session"><span>02</span><h2>{t('listing.couple')}</h2><p>{t('listing.coupleMeta')}</p><strong>{t('listing.explore')}</strong></Link><Link className="listing-card chartreuse" to="/sessions/group-session"><span>03</span><h2>{t('listing.group')}</h2><p>{t('listing.groupMeta')}</p><strong>{t('listing.explore')}</strong></Link></>:<><Link className="listing-card chartreuse" to="/activities/discussion-circle"><span>01</span><h2>{t('listing.discussion')}</h2><p>{t('listing.discussionMeta')}</p><strong>{t('listing.explore')}</strong></Link><Link className="listing-card ice" to="/programs/common-club"><span>02</span><h2>{t('listing.community')}</h2><p>{t('listing.communityMeta')}</p><strong>{t('listing.explore')}</strong></Link></>}</section></main>
}

function ProgramsPage() { const {t}=useTranslation(); const statuses=t('statuses',{returnObjects:true}); return <main><section className="page-intro"><p className="eyebrow">{t('listing.programsKicker')}</p><h1>{t('listing.programsTitle')}</h1></section><section className="listing-grid three">{programs.map((p,i)=><Link className={`listing-card ${p.className}`} to={p.path} key={p.path}><span>{statuses[i]}</span><h2>{p.name}</h2><strong>{t('listing.open')}</strong></Link>)}</section></main> }

function OrientationPage() { const {t}=useTranslation(); const facts=t('orientationPage.facts',{returnObjects:true}); return <main><section className="page-intro"><p className="eyebrow">{t('orientationPage.kicker')}</p><h1>{t('orientationPage.title')}</h1><p className="lead">{t('orientationPage.intro')}</p><div className="button-row"><a className="button" href="mailto:info@houseofhoki.com?subject=Orientation%20call%20request">{t('orientationPage.email')} <span>→</span></a><Link className="text-link" to="/contact">{t('orientationPage.other')} <span>↗</span></Link></div></section><section className="detail-facts">{facts.map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section></main> }

function ContactPage() { const {t}=useTranslation(); return <main><section className="page-intro"><p className="eyebrow">{t('contactPage.kicker')}</p><h1>{t('contactPage.title')}</h1><p className="lead">{t('contactPage.intro')}</p></section><section className="contact-grid"><a href="mailto:info@houseofhoki.com"><span>Email</span><strong>info@houseofhoki.com</strong></a><article><span>{t('contactPage.germany')}</span><strong>{t('contactPage.germanyText')}</strong></article><article><span>{t('contactPage.armenia')}</span><strong>{t('contactPage.armeniaText')}</strong></article></section><CrisisNotice/></main> }

function CrisisNotice() { const {t}=useTranslation(); return <aside className="crisis-notice"><strong>{t('crisis.title')}</strong><p>{t('crisis.text')}</p><Link to="/emergency-support">{t('crisis.link')}</Link></aside> }

function EmergencyPage() { const {t}=useTranslation(); const cards=t('emergency.cards',{returnObjects:true}); const links=['https://gesund.bund.de/en/notfallnummern','https://www.telefonseelsorge.de/','https://mia.gov.am/%D5%A1%D5%B0%D5%A1%D5%A6%D5%A1%D5%B6%D5%A3%D5%A5%D6%80%D5%AB-%D5%AF%D5%A1%D5%BC%D5%A1%D5%BE%D5%A1%D6%80%D5%B8%D6%82%D5%B4/','https://www.yerevan.am/en/news/erewani-k-aghak-apetarane-hogekan-arhoghjowt-yan-irazekman-nakhadzerhnowt-yown-hk-i-het-miasin-iraka/']; return <main><section className="page-intro"><p className="eyebrow">{t('emergency.kicker')}</p><h1>{t('emergency.title')}</h1><p className="lead">{t('emergency.intro')}</p></section><section className="support-grid">{cards.map(([label,number,link],i)=><article key={label}><span>{label}</span><h2>{number}</h2><a href={links[i]} target="_blank" rel="noreferrer">{link}</a></article>)}</section></main> }

function SimplePage({ kicker, title, children, after=null }) { return <main><section className="page-intro"><p className="eyebrow">{kicker}</p><h1>{title}</h1><div className="prose">{children}</div></section>{after}</main> }

function BookingPage({ lang }) { const {search}=useLocation(); const {t}=useTranslation(); const initialService=new URLSearchParams(search).get('service')||''; return <main className="booking-page"><div className="booking-heading"><p className="eyebrow">{t('bookingKicker')}</p><h1>{t('bookingTitle')}</h1><p className="booking-intro">{t('bookingIntro')}</p></div><div className="estimator-embedded"><BookingPlanner key={`${lang}-${initialService}`} lang={lang} initialService={initialService}/></div><CrisisNotice/></main> }

function ScrollManager() { const { pathname }=useLocation(); useEffect(()=>{window.scrollTo(0,0)},[pathname]); return null }

function Footer({onCookieSettings}) { const {t}=useTranslation(); const footerLinks=t('footerLinks',{returnObjects:true}); const legal=t('legalLinks',{returnObjects:true}); return <footer><div><Logo/><p>{t('footer')}</p></div><div className="footer-links"><Link to="/sessions">{footerLinks[0]}</Link><Link to="/programs">{footerLinks[1]}</Link><Link to="/resources">{footerLinks[2]}</Link><Link to="/contact">{footerLinks[3]}</Link></div><div className="footer-meta"><span>© 2026 House of Hoki</span><span><Link to="/privacy">{legal[0]}</Link> · <Link to="/cookies">{legal[1]}</Link> · <button className="footer-cookie-button" onClick={onCookieSettings}>{t('cookieBanner.settingsTitle')}</button> · <Link to="/imprint">{legal[2]}</Link></span><strong>{t('ageNote')}</strong></div></footer> }

function CookieBanner({currentChoice,onChoose,onClose}) { const {t}=useTranslation(); const [details,setDetails]=useState(Boolean(currentChoice)); const [allowLanguage,setAllowLanguage]=useState(currentChoice==='preferences'); return <div className="cookie-backdrop"><aside className="cookie-banner" role="dialog" aria-modal="true" aria-labelledby="cookie-title"><div className="cookie-copy"><strong id="cookie-title">{t(details?'cookieBanner.settingsTitle':'cookieBanner.title')}</strong><p>{t('cookieBanner.text')}</p><Link to="/cookies" onClick={onClose}>{t('cookieBanner.policy')} →</Link></div>{details&&<div className="cookie-categories"><label className="cookie-category"><span><strong>{t('cookieBanner.necessary')}</strong><small>{t('cookieBanner.necessaryText')}</small></span><input type="checkbox" checked disabled aria-label={t('cookieBanner.necessary')}/></label><label className="cookie-category"><span><strong>{t('cookieBanner.preferenceCategory')}</strong><small>{t('cookieBanner.preferenceText')}</small></span><input type="checkbox" checked={allowLanguage} onChange={e=>setAllowLanguage(e.target.checked)} aria-label={t('cookieBanner.preferenceCategory')}/></label></div>}<div className="cookie-actions">{details?<><button className="cookie-button secondary" onClick={()=>onChoose('essential')}>{t('cookieBanner.reject')}</button><button className="cookie-button primary" onClick={()=>onChoose(allowLanguage?'preferences':'essential')}>{t('cookieBanner.save')}</button></>:<><button className="cookie-button secondary" onClick={()=>onChoose('essential')}>{t('cookieBanner.reject')}</button><button className="cookie-button secondary" onClick={()=>setDetails(true)}>{t('cookieBanner.customize')}</button><button className="cookie-button primary" onClick={()=>onChoose('preferences')}>{t('cookieBanner.accept')}</button></>}</div></aside></div> }

function Site() {
  const {t,i18n}=useTranslation()
  const lang=i18n.resolvedLanguage||'en'
  const readCookie=name=>document.cookie.match(new RegExp(`(?:^|; )${name}=([^;]*)`))?.[1]
  const [cookieChoice,setCookieChoice]=useState(()=>readCookie('hoki_cookie_choice')||'')
  const [showCookieSettings,setShowCookieSettings]=useState(()=>!readCookie('hoki_cookie_choice'))
  const saveCookie=(name,value)=>{document.cookie=`${name}=${encodeURIComponent(value)}; Max-Age=31536000; Path=/; SameSite=Lax${location.protocol==='https:'?'; Secure':''}`}
  const removeCookie=name=>{document.cookie=`${name}=; Max-Age=0; Path=/; SameSite=Lax${location.protocol==='https:'?'; Secure':''}`}
  const setLang=value=>{i18n.changeLanguage(value);if(cookieChoice==='preferences')saveCookie('hoki_lang',value)}
  const chooseCookies=choice=>{setCookieChoice(choice);setShowCookieSettings(false);saveCookie('hoki_cookie_choice',choice);if(choice==='preferences')saveCookie('hoki_lang',lang);else removeCookie('hoki_lang')}
  useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir='ltr'},[lang])
  const pages=t('pages',{returnObjects:true})
  const simple=(key,withCrisis=false)=>{const [kicker,title,...paragraphs]=pages[key];return <SimplePage kicker={kicker} title={title} after={withCrisis?<CrisisNotice/>:null}>{paragraphs.map(text=><p key={text}>{text}</p>)}</SimplePage>}
  return <><ScrollManager/><Header lang={lang} setLang={setLang}/><Routes><Route path="/" element={<HomePage lang={lang}/>}/><Route path="/sessions" element={<ListingPage type="sessions"/>}/><Route path="/activities" element={<ListingPage type="activities"/>}/><Route path="/programs" element={<ProgramsPage/>}/>{Object.entries(routePages[lang]||routePages.en).map(([path,page])=><Route key={`${lang}-${path}`} path={path} element={<DetailPage page={page}/>}/>)}<Route path="/booking" element={<BookingPage lang={lang}/>}/><Route path="/orientation-call" element={<OrientationPage/>}/><Route path="/contact" element={<ContactPage/>}/><Route path="/emergency-support" element={<EmergencyPage/>}/><Route path="/about" element={simple('about')}/><Route path="/resources" element={simple('resources',true)}/><Route path="/privacy" element={simple('privacy')}/><Route path="/cookies" element={simple('cookies')}/><Route path="/imprint" element={simple('imprint')}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes><Footer onCookieSettings={()=>setShowCookieSettings(true)}/>{showCookieSettings&&<CookieBanner currentChoice={cookieChoice} onChoose={chooseCookies} onClose={()=>setShowCookieSettings(false)}/>}</>
}

createRoot(document.getElementById('root')).render(<HashRouter><Site/></HashRouter>)
